#!/bin/bash
#PBS -l select=1:ncpus=2:mpiprocs=1
#PBS -P CBBI1243
#PBS -N buildRecal
#PBS -q serial
#PBS -l walltime=6:30:00
#PBS -o /mnt/lustre/users/jmorrice/projects/fifty-genomes/reports/qsub/buildRecal.out
#PBS -e /mnt/lustre/users/jmorrice/projects/fifty-genomes/reports/qsub/buildRecal.err
#PBS -m abe
#PBS -M jackmo375@gmail.com

cd /mnt/lustre/users/jmorrice/projects/fifty-genomes
./templates/pre-processing/build-base-recalibration-model.sh || { exit 1; }
