#!/bin/bash
#PBS -l select=1:ncpus=2:mpiprocs=1
#PBS -P CBBI1243
#PBS -N compareBQSR
#PBS -q serial
#PBS -l walltime=4:00:00
#PBS -o /mnt/lustre/users/jmorrice/projects/fifty-genomes/reports/qsub/compareBQSR.out
#PBS -e /mnt/lustre/users/jmorrice/projects/fifty-genomes/reports/qsub/compareBQSR.err
#PBS -m abe
#PBS -M jackmo375@gmail.com

cd /mnt/lustre/users/jmorrice/projects/fifty-genomes
./templates/pre-processing/compare-pre-and-post-base-recalibration-models.sh || { exit 1; }
